### ISSUE TITLE
semver in packages are causing breaking changes

### ISSUE THREAD

**Issue by Naturalclar** [phenyl/phenyl#298]
1.0.2 contains breaking change in types.

Trying to use phenyl 1.0.1 causes an error, since the monorepo dependencies are labeled in hat notation (`^1.x.x`), causing packages to depend on latest version 1.x.x.

In order to prevent this from happening, we should publish 1.0.1 as 1.2.0,
and release version past 1.0.2 as 2.0.0.

**Comment by sasurau4** [comment]
It's not problem
