### ISSUE TITLE
Update libs

### ISSUE THREAD

**Issue by sasurau4** [phenyl/phenyl#300]
## Overview

Update dependencies

- [x] api-explorer-client @yuuyu00
- [x] api-explorer @sasurau4 
- [x] central-state @Naturalclar 
- [x] express @Naturalclar 
- [x] http-client @sasurau4 
- [x] http-rules @winky 
- [x] http-server @sasurau4
- [x] interfaces @sasurau4 
- [x] lambda-adapter @grgr-dkrk
- [x] memory-db @Leko 
- [x] mongodb @winky 
- [x] redux @grgr-dkrk
- [x] rest-api @1natsu172
- [x] standards @yuuyu00
- [x] state @1natsu172 
- [x] utils @1natsu172
- [x] websocket-client @grgr-dkrk 
- [x] webcokset-server @grgr-dkrk 
- [ ] root package.json

**Comment by Naturalclar** [comment]
I'll take `express`

**Comment by grgr-dkrk** [comment]
redux

**Comment by sasurau4** [comment]
I'll take interface

**Comment by winky** [comment]
I'll take mongodb

**Comment by sasurau4** [comment]
I'll take http-client

**Comment by Leko** [comment]
I'll take memory-db

**Comment by grgr-dkrk** [comment]
I'll take  lambda-adapter

**Comment by 1natsu172** [comment]
i'll take utils

**Comment by sasurau4** [comment]
I'll take http-server

**Comment by Naturalclar** [comment]
I'll take central-state

**Comment by yuuyu00** [comment]
I'll take api-explorer-client

**Comment by winky** [comment]
I'll take http-rules

**Comment by sasurau4** [comment]
I'll api-explorer

**Comment by grgr-dkrk** [comment]
I'll take webcokset-server

**Comment by 1natsu172** [comment]
i'll take rest-api

**Comment by grgr-dkrk** [comment]
I'll take websocket-client

**Comment by 1natsu172** [comment]
i'll take `state`.

**Comment by yuuyu00** [comment]
I'll take standards

**Comment by Naturalclar** [comment]
Thanks Everyone!
