### ISSUE TITLE
Migrate to Jest

### ISSUE THREAD

**Issue by sasurau4** [phenyl/phenyl#302]
## Overview

Phenyl use `nyc` and `mocha`.
We want to migrate `Jest`.
Please replace them!

## Lists

- [ ] api-explorer-client
- [ ] api-explorer
- [ ] central-state
- [ ] express
- [ ] http-client
- [ ] http-rules
- [ ] http-server
- [ ] interfaces
- [ ] lambda-adapter
- [ ] memory-db
- [ ] mongodb
- [ ] redux
- [ ] rest-api
- [ ] standards
- [ ] state
- [ ] utils
- [ ] websocket-client
- [ ] webcokset-server

**Comment by yuuyu00** [comment]
I'll take express
